[project]
name = "various-compilers"
version = "0.1.0"
description = "Compilers and repls for various programming languages"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.4.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
    "ty>=0.0.42",
]

[tool.uv.workspace]
members = [
	"py_apps/*",
	"py_libs/*"
]
